// This file is auto-generated by @hey-api/openapi-ts

export const AIProviderInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        available: {
            type: 'boolean',
            title: 'Available'
        },
        default_model: {
            type: 'string',
            title: 'Default Model'
        },
        models: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Models'
        }
    },
    type: 'object',
    required: ['id', 'name', 'available', 'default_model', 'models'],
    title: 'AIProviderInfo'
} as const;

export const AIProvidersPublicSchema = {
    properties: {
        providers: {
            items: {
                '$ref': '#/components/schemas/AIProviderInfo'
            },
            type: 'array',
            title: 'Providers'
        }
    },
    type: 'object',
    required: ['providers'],
    title: 'AIProvidersPublic'
} as const;

export const AnalysisPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repo_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repo Id'
        },
        workflow_file_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File Id'
        },
        workflow_file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File Path'
        },
        repo_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo Full Name'
        },
        content_hash: {
            type: 'string',
            title: 'Content Hash'
        },
        status: {
            '$ref': '#/components/schemas/AnalysisStatus'
        },
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        },
        triggered_by: {
            '$ref': '#/components/schemas/AnalysisTrigger'
        },
        branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch'
        },
        commit_sha: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commit Sha'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['id', 'repo_id', 'content_hash', 'status', 'triggered_by'],
    title: 'AnalysisPublic'
} as const;

export const AnalysisStatusSchema = {
    type: 'string',
    enum: ['queued', 'running', 'completed', 'failed', 'no_workflows'],
    title: 'AnalysisStatus'
} as const;

export const AnalysisTriggerSchema = {
    type: 'string',
    enum: ['webhook_push', 'webhook_workflow_run', 'polled_push', 'manual', 'scheduled', 'release'],
    title: 'AnalysisTrigger'
} as const;

export const BatchFixRequestSchema = {
    properties: {
        issue_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Ids'
        }
    },
    type: 'object',
    title: 'BatchFixRequest'
} as const;

export const BillingSubscriptionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tier: {
            '$ref': '#/components/schemas/UserTier'
        },
        analyses_used: {
            type: 'integer',
            title: 'Analyses Used'
        },
        fixes_used: {
            type: 'integer',
            title: 'Fixes Used'
        },
        repos_used: {
            type: 'integer',
            title: 'Repos Used',
            default: 0
        },
        period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period Start'
        },
        period_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period End'
        }
    },
    type: 'object',
    required: ['id', 'tier', 'analyses_used', 'fixes_used'],
    title: 'BillingSubscriptionPublic'
} as const;

export const Body_auth_github_callbackSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^authorization_code$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        code: {
            type: 'string',
            title: 'Code'
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        redirect_uri: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2083,
                    minLength: 1,
                    format: 'uri'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Redirect Uri'
        },
        code_verifier: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Code Verifier'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'Body_auth-github_callback'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CIStatusSchema = {
    type: 'string',
    enum: ['pending', 'success', 'failure', 'none'],
    title: 'CIStatus',
    description: 'Aggregate CI outcome for a PR, from ``check_suite`` webhooks.'
} as const;

export const DynamicAnalysisStatusSchema = {
    type: 'string',
    enum: ['queued', 'running', 'enriched', 'failed'],
    title: 'DynamicAnalysisStatus',
    description: `Lifecycle of the dynamic-analysis enrichment for a \`\`completed\`\`-phase
telemetry run.

Distinct from \`\`TelemetryPhase\`\` (an ingest category — \`\`started\`\` and
\`\`completed\`\` are separate rows): this tracks the worker that turns a
completed run's metrics into persisted \`\`DynamicEnrichment\`\` findings.`
} as const;

export const DynamicEnrichmentPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        telemetry_run_id: {
            type: 'string',
            format: 'uuid',
            title: 'Telemetry Run Id'
        },
        workflow_run_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow Run Id'
        },
        rule_slug: {
            type: 'string',
            title: 'Rule Slug'
        },
        evidence: {
            type: 'string',
            title: 'Evidence'
        },
        recommendation: {
            type: 'string',
            title: 'Recommendation'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'telemetry_run_id', 'rule_slug', 'evidence', 'recommendation'],
    title: 'DynamicEnrichmentPublic',
    description: `A runtime-telemetry finding, exposed for the frontend.

Deliberately thinner than \`\`IssuePublic\`\`: enrichments carry no severity,
category, status/lifecycle, line numbers, or fix linkage, so they are
presented as their own "Runtime findings" class rather than merged into the
static issue list.`
} as const;

export const ExternalRepositoryCreateSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 512,
            title: 'Full Name'
        },
        installation_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Id'
        }
    },
    type: 'object',
    required: ['full_name'],
    title: 'ExternalRepositoryCreate'
} as const;

export const FixDeliveryModeSchema = {
    type: 'string',
    enum: ['pr', 'comment', 'disabled'],
    title: 'FixDeliveryMode'
} as const;

export const FixIssueSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        rule_slug: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rule Slug'
        },
        severity: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IssueSeverity'
                },
                {
                    type: 'null'
                }
            ]
        },
        category: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IssueCategory'
                },
                {
                    type: 'null'
                }
            ]
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        },
        line_start: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Line Start'
        },
        line_end: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Line End'
        }
    },
    type: 'object',
    required: ['id'],
    title: 'FixIssueSummary'
} as const;

export const FixPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workflow_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workflow File Id'
        },
        workflow_file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File Path'
        },
        repo_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo Id'
        },
        pr_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr Id'
        },
        llm_provider: {
            '$ref': '#/components/schemas/LLMProvider'
        },
        llm_model: {
            type: 'string',
            title: 'Llm Model'
        },
        status: {
            '$ref': '#/components/schemas/FixStatus'
        },
        full_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Content'
        },
        base_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Base Content'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        pr_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr Url'
        },
        pr_branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr Branch'
        },
        pr_state: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PullRequestState'
                },
                {
                    type: 'null'
                }
            ]
        },
        comment_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        delivered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivered At'
        },
        issues: {
            items: {
                '$ref': '#/components/schemas/FixIssueSummary'
            },
            type: 'array',
            title: 'Issues',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'workflow_file_id', 'llm_provider', 'llm_model', 'status'],
    title: 'FixPublic'
} as const;

export const FixStatusSchema = {
    type: 'string',
    enum: ['pending', 'generating', 'ready', 'delivering', 'delivered', 'failed', 'rejected_by_user', 'superseded_by_closed_pr', 'superseded_by_deleted_file', 'landed'],
    title: 'FixStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InstallationSyncRequestSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        redirect_uri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Redirect Uri'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'InstallationSyncRequest'
} as const;

export const IssueCategorySchema = {
    type: 'string',
    enum: ['energy', 'reliability', 'security', 'performance', 'maintainability'],
    title: 'IssueCategory'
} as const;

export const IssuePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        analysis_id: {
            type: 'string',
            format: 'uuid',
            title: 'Analysis Id'
        },
        rule_id: {
            type: 'string',
            format: 'uuid',
            title: 'Rule Id'
        },
        rule_slug: {
            type: 'string',
            title: 'Rule Slug'
        },
        severity: {
            '$ref': '#/components/schemas/IssueSeverity'
        },
        category: {
            '$ref': '#/components/schemas/IssueCategory'
        },
        line_start: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Line Start'
        },
        line_end: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Line End'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        context: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Context'
        },
        status: {
            '$ref': '#/components/schemas/IssueStatus'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        resolved_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Resolved At'
        },
        resolution_reason: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/IssueResolutionReason'
                },
                {
                    type: 'null'
                }
            ]
        },
        fix_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fix Id'
        },
        fix_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FixStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        workflow_file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File Path'
        }
    },
    type: 'object',
    required: ['id', 'analysis_id', 'rule_id', 'rule_slug', 'severity', 'category', 'message', 'status'],
    title: 'IssuePublic'
} as const;

export const IssueResolutionReasonSchema = {
    type: 'string',
    enum: ['no_longer_detected', 'file_removed', 'merged'],
    title: 'IssueResolutionReason',
    description: `Why an issue was resolved — an attribute of the \`\`resolved\`\` state.

Kept as a column rather than splitting \`\`resolved\`\` into several states so
the issue graph stays small. Set alongside \`\`resolved_at\`\` and cleared when
a resolved violation recurs.

- \`\`no_longer_detected\`\`: absent from the latest analysis (a manual fix or a
  disabled/removed rule — the two cannot be told apart after the fact).
- \`\`file_removed\`\`: the workflow file was deleted or renamed.
- \`\`merged\`\`: the fix PR was merged, applying the change to the branch.`
} as const;

export const IssueSeveritySchema = {
    type: 'string',
    enum: ['critical', 'high', 'medium', 'low', 'info'],
    title: 'IssueSeverity'
} as const;

export const IssueStatusSchema = {
    type: 'string',
    enum: ['open', 'fix_in_progress', 'resolved', 'ignored'],
    title: 'IssueStatus',
    description: `Derived lifecycle of an issue.

This value is a persisted column computed by a database trigger from
\`\`ignored_at\`\`, \`\`resolved_at\`\` and \`\`fix_id\`\` (see \`\`Issue.status\`\` and
migrations \`\`0022\`\`/\`\`0026\`\`). \`\`ignored\`\` takes precedence over the other
states so a user-dismissed violation stays muted regardless of fix/resolve
activity.`
} as const;

export const LLMProviderSchema = {
    type: 'string',
    enum: ['openai', 'anthropic', 'gemini', 'ollama'],
    title: 'LLMProvider'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrganizationAIUpdateSchema = {
    properties: {
        default_llm_provider: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LLMProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        default_llm_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Llm Model'
        }
    },
    type: 'object',
    title: 'OrganizationAIUpdate'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            '$ref': '#/components/schemas/UserTier'
        },
        default_llm_provider: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LLMProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        default_llm_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Llm Model'
        },
        fix_delivery_mode: {
            '$ref': '#/components/schemas/FixDeliveryMode'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'tier', 'fix_delivery_mode'],
    title: 'OrganizationPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PullRequestPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repo_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repo Id'
        },
        pr_branch: {
            type: 'string',
            title: 'Pr Branch'
        },
        pr_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr Url'
        },
        pr_state: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PullRequestState'
                },
                {
                    type: 'null'
                }
            ]
        },
        ci_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/CIStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        review_decision: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ReviewDecision'
                },
                {
                    type: 'null'
                }
            ]
        },
        mergeable_state: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mergeable State'
        },
        comment_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['id', 'repo_id', 'pr_branch'],
    title: 'PullRequestPublic'
} as const;

export const PullRequestStateSchema = {
    type: 'string',
    enum: ['open', 'draft', 'merged', 'closed'],
    title: 'PullRequestState'
} as const;

export const RepositoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        is_accessible: {
            type: 'boolean',
            title: 'Is Accessible',
            default: true
        },
        is_external: {
            type: 'boolean',
            title: 'Is External',
            default: false
        },
        default_branch: {
            type: 'string',
            title: 'Default Branch'
        },
        auto_fix_enabled: {
            type: 'boolean',
            title: 'Auto Fix Enabled',
            default: false
        },
        tier: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserTier'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        avg_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Score'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        }
    },
    type: 'object',
    required: ['id', 'full_name', 'enabled', 'default_branch'],
    title: 'RepositoryPublic'
} as const;

export const ReviewDecisionSchema = {
    type: 'string',
    enum: ['approved', 'changes_requested', 'review_required', 'none'],
    title: 'ReviewDecision',
    description: 'Latest human review decision for a PR, from ``pull_request_review``.'
} as const;

export const RulePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        category: {
            '$ref': '#/components/schemas/IssueCategory'
        },
        severity: {
            '$ref': '#/components/schemas/IssueSeverity'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'category', 'severity', 'title', 'description', 'enabled'],
    title: 'RulePublic'
} as const;

export const SSESignalSchema = {
    type: 'string',
    enum: ['analysis.queued', 'analysis.started', 'analysis.completed', 'analysis.failed', 'analysis.skipped', 'analysis.no_workflows', 'fix.skipped', 'fix.pending', 'fix.generating', 'fix.ready', 'fix.delivering', 'fix.delivered', 'fix.failed', 'fix.rejected', 'fix.landed', 'pr.opened', 'pr.updated', 'pr.closed', 'pr.merged', 'installation.syncing', 'installation.synced', 'installation.created', 'installation.deleted', 'installation.suspended', 'installation.unsuspended', 'installation.updated', 'repository.added', 'repository.disabled', 'repository.toggled', 'repository.action_pr_opened', 'repository.suspended', 'repository.archived', 'repository.inaccessible', 'repository.restored', 'dynamic.queued', 'dynamic.running', 'dynamic.enriched', 'dynamic.failed'],
    title: 'SSESignal'
} as const;

export const SamplePayloadSchema = {
    properties: {
        workflow_run_id: {
            type: 'integer',
            title: 'Workflow Run Id'
        },
        cpu_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu Percent'
        },
        ram_used_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ram Used Mb'
        },
        disk_used_gb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk Used Gb'
        },
        net_bytes_sent: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Bytes Sent'
        },
        net_bytes_recv: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Bytes Recv'
        }
    },
    type: 'object',
    required: ['workflow_run_id'],
    title: 'SamplePayload'
} as const;

export const TelemetryAveragePublicSchema = {
    properties: {
        run_count: {
            type: 'integer',
            title: 'Run Count',
            default: 0
        },
        sample_count: {
            type: 'integer',
            title: 'Sample Count',
            default: 0
        },
        avg_cpu_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Cpu Percent'
        },
        avg_ram_used_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Ram Used Mb'
        },
        avg_ram_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Ram Percent'
        },
        avg_disk_used_gb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Disk Used Gb'
        },
        avg_net_bytes_sent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Net Bytes Sent'
        },
        avg_net_bytes_recv: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Net Bytes Recv'
        },
        avg_vcpus: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Vcpus'
        }
    },
    type: 'object',
    title: 'TelemetryAveragePublic',
    description: `Averaged telemetry across a repo's runs.

Sample-derived fields are averaged over \`\`TelemetryMetricSample\`\` rows;
run-derived fields (\`\`avg_ram_percent\`\`, \`\`avg_vcpus\`\`) come from the
per-run \`\`metrics\`\`/\`\`runner_specs\`\` JSON. Any field is \`\`None\`\` when no
data supports it.`
} as const;

export const TelemetryPayloadSchema = {
    properties: {
        workflow_run_id: {
            type: 'integer',
            title: 'Workflow Run Id'
        },
        branch: {
            type: 'string',
            title: 'Branch',
            default: ''
        },
        commit_sha: {
            type: 'string',
            title: 'Commit Sha',
            default: ''
        },
        workflow_name: {
            type: 'string',
            title: 'Workflow Name',
            default: ''
        },
        runner_specs: {
            additionalProperties: true,
            type: 'object',
            title: 'Runner Specs',
            default: {}
        },
        metrics: {
            additionalProperties: true,
            type: 'object',
            title: 'Metrics',
            default: {}
        },
        phase: {
            '$ref': '#/components/schemas/TelemetryPhase',
            default: 'completed'
        }
    },
    type: 'object',
    required: ['workflow_run_id'],
    title: 'TelemetryPayload'
} as const;

export const TelemetryPhaseSchema = {
    type: 'string',
    enum: ['started', 'completed'],
    title: 'TelemetryPhase'
} as const;

export const TelemetryRunPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        workflow_run_id: {
            type: 'integer',
            title: 'Workflow Run Id'
        },
        phase: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/TelemetryPhase'
                },
                {
                    type: 'null'
                }
            ]
        },
        dynamic_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DynamicAnalysisStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        runner_specs: {
            additionalProperties: true,
            type: 'object',
            title: 'Runner Specs',
            default: {}
        },
        metrics: {
            additionalProperties: true,
            type: 'object',
            title: 'Metrics',
            default: {}
        },
        collected_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Collected At'
        },
        enrichments: {
            items: {
                '$ref': '#/components/schemas/DynamicEnrichmentPublic'
            },
            type: 'array',
            title: 'Enrichments',
            default: []
        }
    },
    type: 'object',
    required: ['id', 'workflow_run_id'],
    title: 'TelemetryRunPublic'
} as const;

export const TelemetrySummaryPublicSchema = {
    properties: {
        average: {
            '$ref': '#/components/schemas/TelemetryAveragePublic'
        },
        runs: {
            items: {
                '$ref': '#/components/schemas/TelemetryRunPublic'
            },
            type: 'array',
            title: 'Runs',
            default: []
        }
    },
    type: 'object',
    required: ['average'],
    title: 'TelemetrySummaryPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        github_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Username'
        },
        tier: {
            '$ref': '#/components/schemas/UserTier',
            default: 'free'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserTierSchema = {
    type: 'string',
    enum: ['free', 'starter', 'pro', 'ultimate', 'open_source'],
    title: 'UserTier'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkflowDeliverRequestSchema = {
    properties: {
        fix_id: {
            type: 'string',
            format: 'uuid',
            title: 'Fix Id'
        }
    },
    type: 'object',
    required: ['fix_id'],
    title: 'WorkflowDeliverRequest'
} as const;

export const WorkflowFilePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        path: {
            type: 'string',
            title: 'Path'
        },
        raw_content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Raw Content'
        }
    },
    type: 'object',
    required: ['id', 'path'],
    title: 'WorkflowFilePublic'
} as const;
