// This file is auto-generated by @hey-api/openapi-ts

export const AIProviderInfoSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        available: {
            type: 'boolean',
            title: 'Available'
        },
        default_model: {
            type: 'string',
            title: 'Default Model'
        },
        models: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Models'
        }
    },
    type: 'object',
    required: ['id', 'name', 'available', 'default_model', 'models'],
    title: 'AIProviderInfo'
} as const;

export const AIProvidersPublicSchema = {
    properties: {
        providers: {
            items: {
                '$ref': '#/components/schemas/AIProviderInfo'
            },
            type: 'array',
            title: 'Providers'
        }
    },
    type: 'object',
    required: ['providers'],
    title: 'AIProvidersPublic'
} as const;

export const AnalysisPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        repo_id: {
            type: 'string',
            format: 'uuid',
            title: 'Repo Id'
        },
        workflow_file_id: {
            type: 'string',
            format: 'uuid',
            title: 'Workflow File Id'
        },
        workflow_file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File Path'
        },
        repo_full_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo Full Name'
        },
        content_hash: {
            type: 'string',
            title: 'Content Hash'
        },
        status: {
            '$ref': '#/components/schemas/AnalysisStatus'
        },
        score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Score'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        },
        triggered_by: {
            '$ref': '#/components/schemas/AnalysisTrigger'
        },
        branch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Branch'
        },
        commit_sha: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Commit Sha'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        completed_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Completed At'
        }
    },
    type: 'object',
    required: ['id', 'repo_id', 'workflow_file_id', 'content_hash', 'status', 'triggered_by'],
    title: 'AnalysisPublic'
} as const;

export const AnalysisStatusSchema = {
    type: 'string',
    enum: ['pending', 'running', 'completed', 'failed', 'skipped'],
    title: 'AnalysisStatus'
} as const;

export const AnalysisTriggerSchema = {
    type: 'string',
    enum: ['webhook_push', 'webhook_workflow_run', 'manual', 'scheduled'],
    title: 'AnalysisTrigger'
} as const;

export const BatchFixRequestSchema = {
    properties: {
        issue_ids: {
            anyOf: [
                {
                    items: {
                        type: 'string',
                        format: 'uuid'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Issue Ids'
        }
    },
    type: 'object',
    title: 'BatchFixRequest'
} as const;

export const BillingSubscriptionPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        tier: {
            '$ref': '#/components/schemas/UserTier'
        },
        analyses_used: {
            type: 'integer',
            title: 'Analyses Used'
        },
        fixes_used: {
            type: 'integer',
            title: 'Fixes Used'
        },
        repos_used: {
            type: 'integer',
            title: 'Repos Used',
            default: 0
        },
        period_start: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period Start'
        },
        period_end: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Period End'
        }
    },
    type: 'object',
    required: ['id', 'tier', 'analyses_used', 'fixes_used'],
    title: 'BillingSubscriptionPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const ExternalRepositoryCreateSchema = {
    properties: {
        full_name: {
            type: 'string',
            maxLength: 512,
            title: 'Full Name'
        },
        installation_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Installation Id'
        }
    },
    type: 'object',
    required: ['full_name'],
    title: 'ExternalRepositoryCreate'
} as const;

export const FixDeliveryModeSchema = {
    type: 'string',
    enum: ['pr', 'comment', 'disabled'],
    title: 'FixDeliveryMode'
} as const;

export const FixPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        issue_id: {
            type: 'string',
            format: 'uuid',
            title: 'Issue Id'
        },
        llm_provider: {
            '$ref': '#/components/schemas/LLMProvider'
        },
        llm_model: {
            type: 'string',
            title: 'Llm Model'
        },
        status: {
            '$ref': '#/components/schemas/FixStatus'
        },
        diff: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diff'
        },
        diff_patch: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diff Patch'
        },
        pr_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr Url'
        },
        pr_state: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Pr State'
        },
        comment_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comment Url'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        delivered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivered At'
        }
    },
    type: 'object',
    required: ['id', 'issue_id', 'llm_provider', 'llm_model', 'status'],
    title: 'FixPublic'
} as const;

export const FixStatusSchema = {
    type: 'string',
    enum: ['pending', 'generating', 'ready', 'delivering', 'delivered', 'failed', 'rejected'],
    title: 'FixStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const InstallationSyncRequestSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        },
        redirect_uri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Redirect Uri'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'InstallationSyncRequest'
} as const;

export const IssueCategorySchema = {
    type: 'string',
    enum: ['energy', 'reliability', 'security', 'performance', 'maintainability'],
    title: 'IssueCategory'
} as const;

export const IssuePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        analysis_id: {
            type: 'string',
            format: 'uuid',
            title: 'Analysis Id'
        },
        rule_id: {
            type: 'string',
            format: 'uuid',
            title: 'Rule Id'
        },
        rule_slug: {
            type: 'string',
            title: 'Rule Slug'
        },
        severity: {
            '$ref': '#/components/schemas/IssueSeverity'
        },
        category: {
            '$ref': '#/components/schemas/IssueCategory'
        },
        line_start: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Line Start'
        },
        line_end: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Line End'
        },
        message: {
            type: 'string',
            title: 'Message'
        },
        context: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Context'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        fix_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fix Id'
        },
        fix_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/FixStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        workflow_file_path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workflow File Path'
        }
    },
    type: 'object',
    required: ['id', 'analysis_id', 'rule_id', 'rule_slug', 'severity', 'category', 'message'],
    title: 'IssuePublic'
} as const;

export const IssueSeveritySchema = {
    type: 'string',
    enum: ['critical', 'high', 'medium', 'low', 'info'],
    title: 'IssueSeverity'
} as const;

export const LLMProviderSchema = {
    type: 'string',
    enum: ['openai', 'anthropic', 'gemini', 'ollama'],
    title: 'LLMProvider'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const OrganizationAIUpdateSchema = {
    properties: {
        default_llm_provider: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LLMProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        default_llm_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Llm Model'
        }
    },
    type: 'object',
    title: 'OrganizationAIUpdate'
} as const;

export const OrganizationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            '$ref': '#/components/schemas/UserTier'
        },
        default_llm_provider: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LLMProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        default_llm_model: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Default Llm Model'
        },
        fix_delivery_mode: {
            '$ref': '#/components/schemas/FixDeliveryMode'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['id', 'name', 'tier', 'fix_delivery_mode'],
    title: 'OrganizationPublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const RepositoryPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        },
        is_external: {
            type: 'boolean',
            title: 'Is External',
            default: false
        },
        default_branch: {
            type: 'string',
            title: 'Default Branch'
        },
        tier: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/UserTier'
                },
                {
                    type: 'null'
                }
            ]
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        avg_score: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avg Score'
        },
        grade: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grade'
        }
    },
    type: 'object',
    required: ['id', 'full_name', 'enabled', 'default_branch'],
    title: 'RepositoryPublic'
} as const;

export const RulePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        category: {
            '$ref': '#/components/schemas/IssueCategory'
        },
        severity: {
            '$ref': '#/components/schemas/IssueSeverity'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'category', 'severity', 'title', 'description', 'enabled'],
    title: 'RulePublic'
} as const;

export const SamplePayloadSchema = {
    properties: {
        workflow_run_id: {
            type: 'integer',
            title: 'Workflow Run Id'
        },
        cpu_percent: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cpu Percent'
        },
        ram_used_mb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ram Used Mb'
        },
        disk_used_gb: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Disk Used Gb'
        },
        net_bytes_sent: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Bytes Sent'
        },
        net_bytes_recv: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Bytes Recv'
        }
    },
    type: 'object',
    required: ['workflow_run_id'],
    title: 'SamplePayload'
} as const;

export const TelemetryPayloadSchema = {
    properties: {
        workflow_run_id: {
            type: 'integer',
            title: 'Workflow Run Id'
        },
        branch: {
            type: 'string',
            title: 'Branch',
            default: ''
        },
        commit_sha: {
            type: 'string',
            title: 'Commit Sha',
            default: ''
        },
        workflow_name: {
            type: 'string',
            title: 'Workflow Name',
            default: ''
        },
        runner_specs: {
            additionalProperties: true,
            type: 'object',
            title: 'Runner Specs',
            default: {}
        },
        metrics: {
            additionalProperties: true,
            type: 'object',
            title: 'Metrics',
            default: {}
        },
        phase: {
            type: 'string',
            title: 'Phase',
            default: 'completed'
        }
    },
    type: 'object',
    required: ['workflow_run_id'],
    title: 'TelemetryPayload'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        github_username: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Github Username'
        },
        tier: {
            '$ref': '#/components/schemas/UserTier',
            default: 'free'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserTierSchema = {
    type: 'string',
    enum: ['free', 'starter', 'pro', 'ultimate', 'open_source'],
    title: 'UserTier'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const WorkflowDeliverRequestSchema = {
    properties: {
        fix_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Fix Ids'
        }
    },
    type: 'object',
    required: ['fix_ids'],
    title: 'WorkflowDeliverRequest'
} as const;
