// This file is auto-generated by @hey-api/openapi-ts

export type AIProviderInfo = {
    id: string;
    name: string;
    available: boolean;
    default_model: string;
    models: Array<(string)>;
};

export type AIProvidersPublic = {
    providers: Array<AIProviderInfo>;
};

export type AnalysisPublic = {
    id: string;
    repo_id: string;
    workflow_file_id?: (string | null);
    workflow_file_path?: (string | null);
    repo_full_name?: (string | null);
    content_hash: string;
    status: AnalysisStatus;
    score?: (number | null);
    grade?: (string | null);
    triggered_by: AnalysisTrigger;
    branch?: (string | null);
    commit_sha?: (string | null);
    created_at?: (string | null);
    completed_at?: (string | null);
};

export type AnalysisStatus = 'queued' | 'running' | 'completed' | 'failed' | 'no_workflows';

export type AnalysisTrigger = 'webhook_push' | 'webhook_workflow_run' | 'manual' | 'scheduled' | 'release';

export type BatchFixRequest = {
    issue_ids?: (Array<(string)> | null);
};

export type BillingSubscriptionPublic = {
    id: string;
    tier: UserTier;
    analyses_used: number;
    fixes_used: number;
    repos_used?: number;
    period_start?: (string | null);
    period_end?: (string | null);
};

export type Body_auth_github_callback = {
    grant_type?: (string | null);
    code: string;
    client_id?: (string | null);
    redirect_uri?: (string | null);
    code_verifier?: (string | null);
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Aggregate CI outcome for a PR, from ``check_suite`` webhooks.
 */
export type CIStatus = 'pending' | 'success' | 'failure' | 'none';

export type ExternalRepositoryCreate = {
    full_name: string;
    installation_id?: (number | null);
};

export type FixDeliveryMode = 'pr' | 'comment' | 'disabled';

export type FixIssueSummary = {
    id: string;
    rule_slug?: (string | null);
    severity?: (IssueSeverity | null);
    category?: (IssueCategory | null);
    message?: (string | null);
    line_start?: (number | null);
    line_end?: (number | null);
};

export type FixPublic = {
    id: string;
    workflow_file_id: string;
    workflow_file_path?: (string | null);
    repo_id?: (string | null);
    pr_id?: (string | null);
    llm_provider: LLMProvider;
    llm_model: string;
    status: FixStatus;
    full_content?: (string | null);
    base_content?: (string | null);
    error_message?: (string | null);
    pr_url?: (string | null);
    pr_branch?: (string | null);
    pr_state?: (PullRequestState | null);
    comment_url?: (string | null);
    created_at?: (string | null);
    delivered_at?: (string | null);
    issues?: Array<FixIssueSummary>;
};

export type FixStatus = 'pending' | 'generating' | 'ready' | 'delivering' | 'delivered' | 'failed' | 'rejected_by_user' | 'superseded_by_closed_pr' | 'superseded_by_deleted_file' | 'landed';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type InstallationSyncRequest = {
    code: string;
    redirect_uri?: (string | null);
};

export type IssueCategory = 'energy' | 'reliability' | 'security' | 'performance' | 'maintainability';

export type IssuePublic = {
    id: string;
    analysis_id: string;
    rule_id: string;
    rule_slug: string;
    severity: IssueSeverity;
    category: IssueCategory;
    line_start?: (number | null);
    line_end?: (number | null);
    message: string;
    context?: (string | null);
    status: IssueStatus;
    created_at?: (string | null);
    resolved_at?: (string | null);
    resolution_reason?: (IssueResolutionReason | null);
    fix_id?: (string | null);
    fix_status?: (FixStatus | null);
    workflow_file_path?: (string | null);
};

/**
 * Why an issue was resolved — an attribute of the ``resolved`` state.
 *
 * Kept as a column rather than splitting ``resolved`` into several states so
 * the issue graph stays small. Set alongside ``resolved_at`` and cleared when
 * a resolved violation recurs.
 *
 * - ``no_longer_detected``: absent from the latest analysis (a manual fix or a
 * disabled/removed rule — the two cannot be told apart after the fact).
 * - ``file_removed``: the workflow file was deleted or renamed.
 * - ``merged``: the fix PR was merged, applying the change to the branch.
 * - ``branch_deleted``: the branch carrying the issue's workflow file was
 * deleted; the violation no longer exists anywhere to fix.
 */
export type IssueResolutionReason = 'no_longer_detected' | 'file_removed' | 'merged' | 'branch_deleted';

export type IssueSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * Derived lifecycle of an issue.
 *
 * This value is a persisted column computed by a database trigger from
 * ``ignored_at``, ``resolved_at`` and ``fix_id`` (see ``Issue.status`` and
 * migrations ``0022``/``0026``). ``ignored`` takes precedence over the other
 * states so a user-dismissed violation stays muted regardless of fix/resolve
 * activity.
 */
export type IssueStatus = 'open' | 'fix_in_progress' | 'resolved' | 'ignored';

export type LLMProvider = 'openai' | 'anthropic' | 'gemini' | 'ollama';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type OrganizationAIUpdate = {
    default_llm_provider?: (LLMProvider | null);
    default_llm_model?: (string | null);
};

export type OrganizationPublic = {
    id: string;
    name: string;
    tier: UserTier;
    default_llm_provider?: (LLMProvider | null);
    default_llm_model?: (string | null);
    fix_delivery_mode: FixDeliveryMode;
    created_at?: (string | null);
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PullRequestPublic = {
    id: string;
    repo_id: string;
    pr_branch: string;
    pr_url?: (string | null);
    pr_state?: (PullRequestState | null);
    ci_status?: (CIStatus | null);
    review_decision?: (ReviewDecision | null);
    mergeable_state?: (string | null);
    externally_modified?: boolean;
    comment_url?: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type PullRequestState = 'open' | 'draft' | 'merged' | 'closed';

export type RepositoryPublic = {
    id: string;
    full_name: string;
    enabled: boolean;
    is_accessible?: boolean;
    is_external?: boolean;
    default_branch: string;
    auto_fix_enabled?: boolean;
    tier?: (UserTier | null);
    created_at?: (string | null);
    avg_score?: (number | null);
    grade?: (string | null);
};

/**
 * Latest human review decision for a PR, from ``pull_request_review``.
 */
export type ReviewDecision = 'approved' | 'changes_requested' | 'review_required' | 'none';

export type RulePublic = {
    id: string;
    slug: string;
    category: IssueCategory;
    severity: IssueSeverity;
    title: string;
    description: string;
    enabled: boolean;
};

export type SamplePayload = {
    workflow_run_id: number;
    cpu_percent?: (number | null);
    ram_used_mb?: (number | null);
    disk_used_gb?: (number | null);
    net_bytes_sent?: (number | null);
    net_bytes_recv?: (number | null);
};

export type SSESignal = 'analysis.queued' | 'analysis.started' | 'analysis.completed' | 'analysis.failed' | 'analysis.skipped' | 'analysis.no_workflows' | 'fix.skipped' | 'fix.pending' | 'fix.generating' | 'fix.ready' | 'fix.delivering' | 'fix.delivered' | 'fix.failed' | 'fix.rejected' | 'fix.landed' | 'pr.opened' | 'pr.updated' | 'pr.closed' | 'pr.merged' | 'installation.syncing' | 'installation.synced' | 'installation.created' | 'installation.deleted' | 'installation.suspended' | 'installation.unsuspended' | 'installation.updated' | 'repository.added' | 'repository.disabled' | 'repository.toggled' | 'repository.action_pr_opened' | 'repository.suspended' | 'repository.archived' | 'repository.inaccessible' | 'repository.restored' | 'dynamic.queued' | 'dynamic.running' | 'dynamic.enriched' | 'dynamic.failed';

export type TelemetryPayload = {
    workflow_run_id: number;
    branch?: string;
    commit_sha?: string;
    workflow_name?: string;
    runner_specs?: {
        [key: string]: unknown;
    };
    metrics?: {
        [key: string]: unknown;
    };
    phase?: TelemetryPhase;
};

export type TelemetryPhase = 'started' | 'completed';

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    github_username?: (string | null);
    tier?: UserTier;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserTier = 'free' | 'starter' | 'pro' | 'ultimate' | 'open_source';

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type WorkflowDeliverRequest = {
    fix_id: string;
};

export type WorkflowFilePublic = {
    id: string;
    path: string;
    branch?: (string | null);
    raw_content?: (string | null);
};

export type AnalysesListAnalysesData = {
    branch?: (string | null);
    grade?: (string | null);
    limit?: number;
    repoId?: (string | null);
    skip?: number;
    status?: (AnalysisStatus | null);
};

export type AnalysesListAnalysesResponse = (Array<AnalysisPublic>);

export type AnalysesGetAnalysisData = {
    analysisId: string;
};

export type AnalysesGetAnalysisResponse = (AnalysisPublic);

export type AnalysesTriggerAnalysisData = {
    branch?: (string | null);
    force?: boolean;
    repoId: string;
};

export type AnalysesTriggerAnalysisResponse = ({
    [key: string]: (string);
});

export type AnalysesReanalyzeAllResponse = ({
    [key: string]: (string);
});

export type AuthGithubCallbackData = {
    formData: Body_auth_github_callback;
};

export type AuthGithubCallbackResponse = (Token);

export type BadgesGetBadgeData = {
    branch: string;
    owner: string;
    repo: string;
};

export type BadgesGetBadgeResponse = (unknown);

export type BadgesGetBadgeJsonData = {
    branch: string;
    owner: string;
    repo: string;
};

export type BadgesGetBadgeJsonResponse = ({
    [key: string]: unknown;
});

export type BillingGetSubscriptionResponse = (BillingSubscriptionPublic);

export type BillingGetTierLimitsResponse = ({
    [key: string]: unknown;
});

export type BillingStripeWebhookData = {
    stripeSignature?: (string | null);
};

export type BillingStripeWebhookResponse = ({
    [key: string]: (string);
});

export type EventsGetSseSignalsResponse = (Array<SSESignal>);

export type EventsCreateSseTicketResponse = ({
    [key: string]: (string | number);
});

export type EventsStreamEventsData = {
    ticket?: (string | null);
};

export type EventsStreamEventsResponse = (unknown);

export type FixesListFixesData = {
    branch?: (string | null);
    limit?: number;
    repoId?: (string | null);
    skip?: number;
    status?: (FixStatus | null);
};

export type FixesListFixesResponse = (Array<FixPublic>);

export type FixesListPullRequestsData = {
    repoId: string;
};

export type FixesListPullRequestsResponse = (Array<PullRequestPublic>);

export type FixesGetFixData = {
    fixId: string;
};

export type FixesGetFixResponse = (FixPublic);

export type FixesRejectFixData = {
    fixId: string;
};

export type FixesRejectFixResponse = (void);

export type FixesTriggerFixGenerationForRepoData = {
    force?: boolean;
    repoId: string;
    requestBody?: BatchFixRequest;
};

export type FixesTriggerFixGenerationForRepoResponse = ({
    [key: string]: (number);
});

export type FixesTriggerWorkflowDeliveryData = {
    force?: boolean;
    requestBody: WorkflowDeliverRequest;
};

export type FixesTriggerWorkflowDeliveryResponse = ({
    [key: string]: (string);
});

export type FixesTriggerRepoDeliveryData = {
    force?: boolean;
    repoId: string;
};

export type FixesTriggerRepoDeliveryResponse = ({
    [key: string]: (string);
});

export type FixesRegenerateFixesForRepoData = {
    repoId: string;
};

export type FixesRegenerateFixesForRepoResponse = ({
    [key: string]: (number);
});

export type FixesRegenerateFixesForWorkflowData = {
    fixId: string;
};

export type FixesRegenerateFixesForWorkflowResponse = ({
    [key: string]: (number);
});

export type FixesRegenerateFailedFixData = {
    fixId: string;
};

export type FixesRegenerateFailedFixResponse = ({
    [key: string]: (string);
});

export type FixesSyncPrStatusesData = {
    repoId: string;
};

export type FixesSyncPrStatusesResponse = ({
    [key: string]: (number);
});

export type InstallationsListInstallationsResponse = (Array<OrganizationPublic>);

export type InstallationsSyncInstallationsData = {
    requestBody: InstallationSyncRequest;
};

export type InstallationsSyncInstallationsResponse = (Array<OrganizationPublic>);

export type IssuesListIssuesData = {
    analysisId?: (string | null);
    branch?: (string | null);
    category?: (IssueCategory | null);
    includeIgnored?: boolean;
    includeResolved?: boolean;
    latestOnly?: boolean;
    limit?: number;
    repoId?: (string | null);
    severity?: (IssueSeverity | null);
    skip?: number;
    unfixed?: boolean;
};

export type IssuesListIssuesResponse = (Array<IssuePublic>);

export type IssuesGetIssueData = {
    issueId: string;
};

export type IssuesGetIssueResponse = (IssuePublic);

export type IssuesIgnoreIssueData = {
    issueId: string;
};

export type IssuesIgnoreIssueResponse = (IssuePublic);

export type IssuesUnignoreIssueData = {
    issueId: string;
};

export type IssuesUnignoreIssueResponse = (IssuePublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type OrganizationsListAiProvidersResponse = (AIProvidersPublic);

export type OrganizationsListMyOrganizationsResponse = (Array<OrganizationPublic>);

export type OrganizationsUpdateOrgAiPreferencesData = {
    orgId: string;
    requestBody: OrganizationAIUpdate;
};

export type OrganizationsUpdateOrgAiPreferencesResponse = (OrganizationPublic);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RepositoriesListRepositoriesData = {
    enabled?: (boolean | null);
    limit?: number;
    orgId?: (string | null);
    skip?: number;
};

export type RepositoriesListRepositoriesResponse = (Array<RepositoryPublic>);

export type RepositoriesListExternalRepositoriesData = {
    limit?: number;
    skip?: number;
};

export type RepositoriesListExternalRepositoriesResponse = (Array<RepositoryPublic>);

export type RepositoriesCreateExternalRepositoryData = {
    requestBody: ExternalRepositoryCreate;
};

export type RepositoriesCreateExternalRepositoryResponse = (RepositoryPublic);

export type RepositoriesGetRepositoryData = {
    repoId: string;
};

export type RepositoriesGetRepositoryResponse = (RepositoryPublic);

export type RepositoriesListWorkflowFilesData = {
    branch?: (string | null);
    repoId: string;
};

export type RepositoriesListWorkflowFilesResponse = (Array<WorkflowFilePublic>);

export type RepositoriesToggleRepositoryData = {
    enabled: boolean;
    repoId: string;
};

export type RepositoriesToggleRepositoryResponse = ({
    [key: string]: (string | boolean);
});

export type RepositoriesToggleAutoFixData = {
    enabled: boolean;
    repoId: string;
};

export type RepositoriesToggleAutoFixResponse = ({
    [key: string]: (string | boolean);
});

export type RepositoriesListRepositoryBranchesData = {
    repoId: string;
};

export type RepositoriesListRepositoryBranchesResponse = (Array<(string)>);

export type RepositoriesIntegrateActionData = {
    repoId: string;
};

export type RepositoriesIntegrateActionResponse = ({
    [key: string]: (string);
});

export type RulesListRulesData = {
    category?: (IssueCategory | null);
    enabled?: (boolean | null);
    limit?: number;
    skip?: number;
};

export type RulesListRulesResponse = (Array<RulePublic>);

export type RulesGetRuleData = {
    ruleId: string;
};

export type RulesGetRuleResponse = (RulePublic);

export type RulesToggleRuleData = {
    enabled: boolean;
    ruleId: string;
};

export type RulesToggleRuleResponse = (RulePublic);

export type TelemetryIngestTelemetryData = {
    authorization?: (string | null);
    requestBody: TelemetryPayload;
};

export type TelemetryIngestTelemetryResponse = ({
    [key: string]: (string);
});

export type TelemetryIngestSampleData = {
    authorization?: (string | null);
    requestBody: SamplePayload;
};

export type TelemetryIngestSampleResponse = ({
    [key: string]: (string);
});

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebhooksGithubWebhookData = {
    xGithubDelivery?: (string | null);
    xGithubEvent?: (string | null);
    xHubSignature256?: (string | null);
};

export type WebhooksGithubWebhookResponse = ({
    [key: string]: (string);
});
