// This file is auto-generated by @hey-api/openapi-ts

/**
 * AIProviderInfo
 */
export type AiProviderInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Available
     */
    available: boolean;
    /**
     * Default Model
     */
    default_model: string;
    /**
     * Models
     */
    models: Array<string>;
};

/**
 * AIProvidersPublic
 */
export type AiProvidersPublic = {
    /**
     * Providers
     */
    providers: Array<AiProviderInfo>;
};

/**
 * AnalysisPublic
 */
export type AnalysisPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Id
     */
    repo_id: string;
    /**
     * Workflow File Id
     */
    workflow_file_id?: string | null;
    /**
     * Workflow File Path
     */
    workflow_file_path?: string | null;
    /**
     * Repo Full Name
     */
    repo_full_name?: string | null;
    /**
     * Content Hash
     */
    content_hash: string;
    status: AnalysisStatus;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Grade
     */
    grade?: string | null;
    triggered_by: AnalysisTrigger;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Commit Sha
     */
    commit_sha?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
};

/**
 * AnalysisStatus
 */
export type AnalysisStatus = 'queued' | 'running' | 'completed' | 'failed' | 'no_workflows';

/**
 * AnalysisTrigger
 */
export type AnalysisTrigger = 'webhook_push' | 'webhook_workflow_run' | 'polled_push' | 'manual' | 'scheduled' | 'release';

/**
 * BatchFixRequest
 */
export type BatchFixRequest = {
    /**
     * Issue Ids
     */
    issue_ids?: Array<string> | null;
};

/**
 * BillingSubscriptionPublic
 */
export type BillingSubscriptionPublic = {
    /**
     * Id
     */
    id: string;
    tier: UserTier;
    /**
     * Analyses Used
     */
    analyses_used: number;
    /**
     * Fixes Used
     */
    fixes_used: number;
    /**
     * Repos Used
     */
    repos_used?: number;
    /**
     * Period Start
     */
    period_start?: string | null;
    /**
     * Period End
     */
    period_end?: string | null;
};

/**
 * Body_auth-github_callback
 */
export type BodyAuthGithubCallback = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Code
     */
    code: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null;
    /**
     * Code Verifier
     */
    code_verifier?: string | null;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * CIStatus
 * Aggregate CI outcome for a PR, from ``check_suite`` webhooks.
 */
export type CiStatus = 'pending' | 'success' | 'failure' | 'none';

/**
 * DynamicAnalysisStatus
 * Lifecycle of the dynamic-analysis enrichment for a ``completed``-phase
 * telemetry run.
 *
 * Distinct from ``TelemetryPhase`` (an ingest category — ``started`` and
 * ``completed`` are separate rows): this tracks the worker that turns a
 * completed run's metrics into persisted ``DynamicEnrichment`` findings.
 */
export type DynamicAnalysisStatus = 'queued' | 'running' | 'enriched' | 'failed';

/**
 * DynamicEnrichmentPublic
 * A runtime-telemetry finding, exposed for the frontend.
 *
 * Deliberately thinner than ``IssuePublic``: enrichments carry no severity,
 * category, status/lifecycle, line numbers, or fix linkage, so they are
 * presented as their own "Runtime findings" class rather than merged into the
 * static issue list.
 */
export type DynamicEnrichmentPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Telemetry Run Id
     */
    telemetry_run_id: string;
    /**
     * Workflow Run Id
     */
    workflow_run_id?: number | null;
    /**
     * Rule Slug
     */
    rule_slug: string;
    /**
     * Evidence
     */
    evidence: string;
    /**
     * Recommendation
     */
    recommendation: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * ExternalRepositoryCreate
 */
export type ExternalRepositoryCreate = {
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Installation Id
     */
    installation_id?: number | null;
};

/**
 * FindingResolutionReason
 */
export type FindingResolutionReason = 'no_longer_detected' | 'target_removed';

/**
 * FindingStatus
 * Lifecycle of a TerraformFinding or CloudFinding.
 *
 * Unlike ``Issue.status`` (owned by a DB trigger reacting to ``fix_id``),
 * findings in this delivery have no fix/PR concept yet (see plan Phase 7),
 * so the application sets this column directly alongside resolved_at/
 * ignored_at rather than needing trigger-derived state.
 */
export type FindingStatus = 'open' | 'resolved' | 'ignored';

/**
 * FixDeliveryMode
 */
export type FixDeliveryMode = 'pr' | 'comment' | 'disabled';

/**
 * FixIssueSummary
 */
export type FixIssueSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Rule Slug
     */
    rule_slug?: string | null;
    severity?: IssueSeverity | null;
    category?: IssueCategory | null;
    /**
     * Message
     */
    message?: string | null;
    /**
     * Line Start
     */
    line_start?: number | null;
    /**
     * Line End
     */
    line_end?: number | null;
};

/**
 * FixPublic
 */
export type FixPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow File Id
     */
    workflow_file_id: string;
    /**
     * Workflow File Path
     */
    workflow_file_path?: string | null;
    /**
     * Repo Id
     */
    repo_id?: string | null;
    /**
     * Pr Id
     */
    pr_id?: string | null;
    llm_provider: LlmProvider;
    /**
     * Llm Model
     */
    llm_model: string;
    status: FixStatus;
    /**
     * Full Content
     */
    full_content?: string | null;
    /**
     * Base Content
     */
    base_content?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Pr Url
     */
    pr_url?: string | null;
    /**
     * Pr Branch
     */
    pr_branch?: string | null;
    pr_state?: PullRequestState | null;
    /**
     * Comment Url
     */
    comment_url?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Delivered At
     */
    delivered_at?: string | null;
    /**
     * Issues
     */
    issues?: Array<FixIssueSummary>;
};

/**
 * FixStatus
 */
export type FixStatus = 'pending' | 'generating' | 'ready' | 'delivering' | 'delivered' | 'failed' | 'rejected_by_user' | 'superseded_by_closed_pr' | 'superseded_by_deleted_file' | 'landed';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * InstallationSyncRequest
 */
export type InstallationSyncRequest = {
    /**
     * Code
     */
    code: string;
    /**
     * Redirect Uri
     */
    redirect_uri?: string | null;
};

/**
 * IssueCategory
 */
export type IssueCategory = 'energy' | 'reliability' | 'security' | 'performance' | 'maintainability';

/**
 * IssueCategoryStat
 */
export type IssueCategoryStat = {
    category: IssueCategory;
    /**
     * Open
     */
    open: number;
    /**
     * Resolved
     */
    resolved: number;
    /**
     * Critical Open
     */
    critical_open: number;
};

/**
 * IssuePublic
 */
export type IssuePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Analysis Id
     */
    analysis_id: string;
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Rule Slug
     */
    rule_slug: string;
    severity: IssueSeverity;
    category: IssueCategory;
    /**
     * Line Start
     */
    line_start?: number | null;
    /**
     * Line End
     */
    line_end?: number | null;
    /**
     * Message
     */
    message: string;
    /**
     * Context
     */
    context?: string | null;
    status: IssueStatus;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Resolved At
     */
    resolved_at?: string | null;
    resolution_reason?: IssueResolutionReason | null;
    /**
     * Needs Manual Work
     */
    needs_manual_work?: boolean;
    /**
     * Manual Work Note
     */
    manual_work_note?: string | null;
    /**
     * Fix Id
     */
    fix_id?: string | null;
    fix_status?: FixStatus | null;
    /**
     * Workflow File Path
     */
    workflow_file_path?: string | null;
};

/**
 * IssueResolutionReason
 * Why an issue was resolved — an attribute of the ``resolved`` state.
 *
 * Kept as a column rather than splitting ``resolved`` into several states so
 * the issue graph stays small. Set alongside ``resolved_at`` and cleared when
 * a resolved violation recurs.
 *
 * - ``no_longer_detected``: absent from the latest analysis (a manual fix or a
 * disabled/removed rule — the two cannot be told apart after the fact).
 * - ``file_removed``: the workflow file was deleted or renamed.
 * - ``merged``: the fix PR was merged, applying the change to the branch.
 * - ``branch_deleted``: the branch carrying the issue's workflow file was
 * deleted; the violation no longer exists anywhere to fix.
 */
export type IssueResolutionReason = 'no_longer_detected' | 'file_removed' | 'merged' | 'branch_deleted';

/**
 * IssueSeverity
 */
export type IssueSeverity = 'critical' | 'high' | 'medium' | 'low' | 'info';

/**
 * IssueStatsPublic
 * Exact issue counts, computed by SQL aggregation rather than fetched and
 * counted client-side — unaffected by any page's ``skip``/``limit``.
 */
export type IssueStatsPublic = {
    /**
     * Total Open
     */
    total_open: number;
    /**
     * Total Resolved
     */
    total_resolved: number;
    /**
     * Critical Open
     */
    critical_open: number;
    /**
     * By Category
     */
    by_category: Array<IssueCategoryStat>;
    /**
     * By Repo
     */
    by_repo?: Array<RepoIssueStats>;
};

/**
 * IssueStatus
 * Derived lifecycle of an issue.
 *
 * This value is a persisted column computed by a database trigger from
 * ``ignored_at``, ``resolved_at`` and ``fix_id`` (see ``Issue.status`` and
 * migrations ``0022``/``0026``). ``ignored`` takes precedence over the other
 * states so a user-dismissed violation stays muted regardless of fix/resolve
 * activity.
 */
export type IssueStatus = 'open' | 'fix_in_progress' | 'resolved' | 'ignored';

/**
 * LLMProvider
 */
export type LlmProvider = 'openai' | 'anthropic' | 'gemini' | 'ollama';

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * OrganizationAIUpdate
 */
export type OrganizationAiUpdate = {
    default_llm_provider?: LlmProvider | null;
    /**
     * Default Llm Model
     */
    default_llm_model?: string | null;
};

/**
 * OrganizationPublic
 */
export type OrganizationPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    tier: UserTier;
    default_llm_provider?: LlmProvider | null;
    /**
     * Default Llm Model
     */
    default_llm_model?: string | null;
    fix_delivery_mode: FixDeliveryMode;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * PullRequestPublic
 */
export type PullRequestPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Id
     */
    repo_id: string;
    /**
     * Pr Branch
     */
    pr_branch: string;
    /**
     * Pr Url
     */
    pr_url?: string | null;
    pr_state?: PullRequestState | null;
    ci_status?: CiStatus | null;
    review_decision?: ReviewDecision | null;
    /**
     * Mergeable State
     */
    mergeable_state?: string | null;
    /**
     * Externally Modified
     */
    externally_modified?: boolean;
    /**
     * Comment Url
     */
    comment_url?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
};

/**
 * PullRequestState
 */
export type PullRequestState = 'open' | 'draft' | 'merged' | 'closed';

/**
 * RepoCategoryStat
 * A repo's open-issue counts and severity-weighted grade for one category.
 *
 * ``score``/``grade`` are ``None`` when the repo has no overall grade yet
 * (e.g. no completed analysis). See ``RepoIssueStats`` for how categories
 * are grouped per repo.
 */
export type RepoCategoryStat = {
    category: IssueCategory;
    /**
     * Open
     */
    open: number;
    /**
     * Critical Open
     */
    critical_open: number;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Grade
     */
    grade?: string | null;
};

/**
 * RepoIssueStats
 * Per-repo issue breakdown — powers the dashboard's category health star
 * diagram. Only populated on the unscoped (all-repos) stats call;
 * meaningless once already filtered to a single ``repo_id``.
 *
 * ``score``/``grade`` here are the repo's own overall grade (same values as
 * ``RepositoryPublic.avg_score``/``grade``), repeated so the frontend
 * doesn't need a second lookup to size the radar's "no issues" fallback.
 * Each entry in ``categories`` covers every ``IssueCategory``, including
 * categories with zero open issues, so their scores average out to exactly
 * the repo's overall score (see ``compute_category_scores``).
 */
export type RepoIssueStats = {
    /**
     * Repo Id
     */
    repo_id: string;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Grade
     */
    grade?: string | null;
    /**
     * Categories
     */
    categories?: Array<RepoCategoryStat>;
};

/**
 * RepositoryPublic
 */
export type RepositoryPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Is Accessible
     */
    is_accessible?: boolean;
    /**
     * Is External
     */
    is_external?: boolean;
    /**
     * Is Private
     */
    is_private?: boolean;
    /**
     * Default Branch
     */
    default_branch: string;
    /**
     * Auto Fix Enabled
     */
    auto_fix_enabled?: boolean;
    tier?: UserTier | null;
    /**
     * Badge Sig
     */
    badge_sig?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Avg Score
     */
    avg_score?: number | null;
    /**
     * Grade
     */
    grade?: string | null;
};

/**
 * ReviewDecision
 * Latest human review decision for a PR, from ``pull_request_review``.
 */
export type ReviewDecision = 'approved' | 'changes_requested' | 'review_required';

/**
 * RulePublic
 */
export type RulePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Slug
     */
    slug: string;
    category: IssueCategory;
    severity: IssueSeverity;
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description: string;
    /**
     * Enabled
     */
    enabled: boolean;
};

/**
 * SSESignal
 */
export type SseSignal = 'analysis.queued' | 'analysis.started' | 'analysis.completed' | 'analysis.failed' | 'analysis.skipped' | 'analysis.no_workflows' | 'fix.skipped' | 'fix.pending' | 'fix.generating' | 'fix.ready' | 'fix.delivering' | 'fix.delivered' | 'fix.failed' | 'fix.rejected' | 'fix.landed' | 'pr.opened' | 'pr.updated' | 'pr.closed' | 'pr.merged' | 'installation.syncing' | 'installation.synced' | 'installation.created' | 'installation.deleted' | 'installation.suspended' | 'installation.unsuspended' | 'installation.updated' | 'repository.added' | 'repository.disabled' | 'repository.toggled' | 'repository.action_pr_opened' | 'repository.suspended' | 'repository.archived' | 'repository.inaccessible' | 'repository.restored' | 'dynamic.queued' | 'dynamic.running' | 'dynamic.enriched' | 'dynamic.failed';

/**
 * SamplePayload
 */
export type SamplePayload = {
    /**
     * Workflow Run Id
     */
    workflow_run_id: number;
    /**
     * Cpu Percent
     */
    cpu_percent?: number | null;
    /**
     * Ram Used Mb
     */
    ram_used_mb?: number | null;
    /**
     * Disk Used Gb
     */
    disk_used_gb?: number | null;
    /**
     * Net Bytes Sent
     */
    net_bytes_sent?: number | null;
    /**
     * Net Bytes Recv
     */
    net_bytes_recv?: number | null;
    /**
     * Top Processes
     */
    top_processes?: Array<{
        [key: string]: unknown;
    }> | null;
};

/**
 * ScanStatus
 * Lifecycle of a TerraformScan or CloudScan.
 *
 * Deliberately separate from ``AnalysisStatus``: that enum's ``no_workflows``
 * value is workflow-specific vocabulary. ``no_targets`` covers both "no .tf
 * files under this root" and "no resources of the scanned types in this
 * account/region".
 */
export type ScanStatus = 'queued' | 'running' | 'completed' | 'failed' | 'no_targets';

/**
 * TelemetryAveragePublic
 * Averaged telemetry across a repo's runs.
 *
 * Sample-derived fields are averaged over ``TelemetryMetricSample`` rows;
 * run-derived fields (``avg_ram_percent``, ``avg_vcpus``) come from the
 * per-run ``metrics``/``runner_specs`` JSON. Any field is ``None`` when no
 * data supports it.
 */
export type TelemetryAveragePublic = {
    /**
     * Run Count
     */
    run_count?: number;
    /**
     * Sample Count
     */
    sample_count?: number;
    /**
     * Avg Cpu Percent
     */
    avg_cpu_percent?: number | null;
    /**
     * Avg Ram Used Mb
     */
    avg_ram_used_mb?: number | null;
    /**
     * Avg Ram Percent
     */
    avg_ram_percent?: number | null;
    /**
     * Avg Disk Used Gb
     */
    avg_disk_used_gb?: number | null;
    /**
     * Avg Net Bytes Sent
     */
    avg_net_bytes_sent?: number | null;
    /**
     * Avg Net Bytes Recv
     */
    avg_net_bytes_recv?: number | null;
    /**
     * Avg Vcpus
     */
    avg_vcpus?: number | null;
};

/**
 * TelemetryPayload
 */
export type TelemetryPayload = {
    /**
     * Workflow Run Id
     */
    workflow_run_id: number;
    /**
     * Branch
     */
    branch?: string;
    /**
     * Commit Sha
     */
    commit_sha?: string;
    /**
     * Workflow Name
     */
    workflow_name?: string;
    /**
     * Runner Specs
     */
    runner_specs?: {
        [key: string]: unknown;
    };
    /**
     * Metrics
     */
    metrics?: {
        [key: string]: unknown;
    };
    phase?: TelemetryPhase;
};

/**
 * TelemetryPhase
 */
export type TelemetryPhase = 'started' | 'completed';

/**
 * TelemetryRunPublic
 */
export type TelemetryRunPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Workflow Run Id
     */
    workflow_run_id: number;
    phase?: TelemetryPhase | null;
    dynamic_status?: DynamicAnalysisStatus | null;
    /**
     * Runner Specs
     */
    runner_specs?: {
        [key: string]: unknown;
    };
    /**
     * Metrics
     */
    metrics?: {
        [key: string]: unknown;
    };
    /**
     * Collected At
     */
    collected_at?: string | null;
    /**
     * Enrichments
     */
    enrichments?: Array<DynamicEnrichmentPublic>;
};

/**
 * TelemetrySummaryPublic
 */
export type TelemetrySummaryPublic = {
    average: TelemetryAveragePublic;
    /**
     * Runs
     */
    runs?: Array<TelemetryRunPublic>;
};

/**
 * TerraformFindingPublic
 */
export type TerraformFindingPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Scan Id
     */
    scan_id: string;
    /**
     * Terraform Root Id
     */
    terraform_root_id: string;
    /**
     * Rule Id
     */
    rule_id: string;
    /**
     * Rule Slug
     */
    rule_slug: string;
    /**
     * Resource Address
     */
    resource_address?: string | null;
    /**
     * File Path
     */
    file_path: string;
    severity: IssueSeverity;
    category: IssueCategory;
    /**
     * Message
     */
    message: string;
    /**
     * Context
     */
    context?: string | null;
    status: FindingStatus;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Resolved At
     */
    resolved_at?: string | null;
    resolution_reason?: FindingResolutionReason | null;
};

/**
 * TerraformRootCreate
 */
export type TerraformRootCreate = {
    /**
     * Repo Id
     */
    repo_id: string;
    /**
     * Root Path
     */
    root_path: string;
};

/**
 * TerraformRootPublic
 */
export type TerraformRootPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Repo Id
     */
    repo_id: string;
    /**
     * Repo Full Name
     */
    repo_full_name?: string | null;
    /**
     * Root Path
     */
    root_path: string;
    /**
     * Enabled
     */
    enabled: boolean;
    /**
     * Last Scanned At
     */
    last_scanned_at?: string | null;
    /**
     * Last Scanned Head Sha
     */
    last_scanned_head_sha?: string | null;
    /**
     * Latest Score
     */
    latest_score?: number | null;
    /**
     * Latest Grade
     */
    latest_grade?: string | null;
};

/**
 * TerraformScanPublic
 */
export type TerraformScanPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Terraform Root Id
     */
    terraform_root_id: string;
    status: ScanStatus;
    triggered_by: AnalysisTrigger;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Commit Sha
     */
    commit_sha?: string | null;
    /**
     * Score
     */
    score?: number | null;
    /**
     * Grade
     */
    grade?: string | null;
    /**
     * Error Message
     */
    error_message?: string | null;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Completed At
     */
    completed_at?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Github Username
     */
    github_username?: string | null;
    tier?: UserTier;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserTier
 */
export type UserTier = 'free' | 'starter' | 'pro' | 'ultimate' | 'open_source';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WorkflowDeliverRequest
 */
export type WorkflowDeliverRequest = {
    /**
     * Fix Id
     */
    fix_id: string;
};

/**
 * WorkflowFilePublic
 */
export type WorkflowFilePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Path
     */
    path: string;
    /**
     * Branch
     */
    branch?: string | null;
    /**
     * Raw Content
     */
    raw_content?: string | null;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type UtilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UtilsTestEmailError = UtilsTestEmailErrors[keyof UtilsTestEmailErrors];

export type UtilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type UtilsTestEmailResponse = UtilsTestEmailResponses[keyof UtilsTestEmailResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type AuthGithubCallbackData = {
    body: BodyAuthGithubCallback;
    path?: never;
    query?: never;
    url: '/api/v1/auth/github/callback';
};

export type AuthGithubCallbackErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthGithubCallbackError = AuthGithubCallbackErrors[keyof AuthGithubCallbackErrors];

export type AuthGithubCallbackResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type AuthGithubCallbackResponse = AuthGithubCallbackResponses[keyof AuthGithubCallbackResponses];

export type InstallationsListInstallationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/installations/';
};

export type InstallationsListInstallationsResponses = {
    /**
     * Response Installations-List Installations
     * Successful Response
     */
    200: Array<OrganizationPublic>;
};

export type InstallationsListInstallationsResponse = InstallationsListInstallationsResponses[keyof InstallationsListInstallationsResponses];

export type InstallationsSyncInstallationsData = {
    body: InstallationSyncRequest;
    path?: never;
    query?: never;
    url: '/api/v1/installations/sync';
};

export type InstallationsSyncInstallationsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type InstallationsSyncInstallationsError = InstallationsSyncInstallationsErrors[keyof InstallationsSyncInstallationsErrors];

export type InstallationsSyncInstallationsResponses = {
    /**
     * Response Installations-Sync Installations
     * Successful Response
     */
    200: Array<OrganizationPublic>;
};

export type InstallationsSyncInstallationsResponse = InstallationsSyncInstallationsResponses[keyof InstallationsSyncInstallationsResponses];

export type OrganizationsListAiProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/ai-providers';
};

export type OrganizationsListAiProvidersResponses = {
    /**
     * Successful Response
     */
    200: AiProvidersPublic;
};

export type OrganizationsListAiProvidersResponse = OrganizationsListAiProvidersResponses[keyof OrganizationsListAiProvidersResponses];

export type OrganizationsListMyOrganizationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/';
};

export type OrganizationsListMyOrganizationsResponses = {
    /**
     * Response Organizations-List My Organizations
     * Successful Response
     */
    200: Array<OrganizationPublic>;
};

export type OrganizationsListMyOrganizationsResponse = OrganizationsListMyOrganizationsResponses[keyof OrganizationsListMyOrganizationsResponses];

export type OrganizationsUpdateOrgAiPreferencesData = {
    body: OrganizationAiUpdate;
    path: {
        /**
         * Org Id
         */
        org_id: string;
    };
    query?: never;
    url: '/api/v1/organizations/{org_id}/ai-preferences';
};

export type OrganizationsUpdateOrgAiPreferencesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OrganizationsUpdateOrgAiPreferencesError = OrganizationsUpdateOrgAiPreferencesErrors[keyof OrganizationsUpdateOrgAiPreferencesErrors];

export type OrganizationsUpdateOrgAiPreferencesResponses = {
    /**
     * Successful Response
     */
    200: OrganizationPublic;
};

export type OrganizationsUpdateOrgAiPreferencesResponse = OrganizationsUpdateOrgAiPreferencesResponses[keyof OrganizationsUpdateOrgAiPreferencesResponses];

export type RepositoriesListRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Org Id
         */
        org_id?: string | null;
        /**
         * Enabled
         */
        enabled?: boolean | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/';
};

export type RepositoriesListRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesListRepositoriesError = RepositoriesListRepositoriesErrors[keyof RepositoriesListRepositoriesErrors];

export type RepositoriesListRepositoriesResponses = {
    /**
     * Response Repositories-List Repositories
     * Successful Response
     */
    200: Array<RepositoryPublic>;
};

export type RepositoriesListRepositoriesResponse = RepositoriesListRepositoriesResponses[keyof RepositoriesListRepositoriesResponses];

export type RepositoriesListExternalRepositoriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/repositories/external';
};

export type RepositoriesListExternalRepositoriesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesListExternalRepositoriesError = RepositoriesListExternalRepositoriesErrors[keyof RepositoriesListExternalRepositoriesErrors];

export type RepositoriesListExternalRepositoriesResponses = {
    /**
     * Response Repositories-List External Repositories
     * Successful Response
     */
    200: Array<RepositoryPublic>;
};

export type RepositoriesListExternalRepositoriesResponse = RepositoriesListExternalRepositoriesResponses[keyof RepositoriesListExternalRepositoriesResponses];

export type RepositoriesCreateExternalRepositoryData = {
    body: ExternalRepositoryCreate;
    path?: never;
    query?: never;
    url: '/api/v1/repositories/external';
};

export type RepositoriesCreateExternalRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesCreateExternalRepositoryError = RepositoriesCreateExternalRepositoryErrors[keyof RepositoriesCreateExternalRepositoryErrors];

export type RepositoriesCreateExternalRepositoryResponses = {
    /**
     * Successful Response
     */
    201: RepositoryPublic;
};

export type RepositoriesCreateExternalRepositoryResponse = RepositoriesCreateExternalRepositoryResponses[keyof RepositoriesCreateExternalRepositoryResponses];

export type RepositoriesGetRepositoryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}';
};

export type RepositoriesGetRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesGetRepositoryError = RepositoriesGetRepositoryErrors[keyof RepositoriesGetRepositoryErrors];

export type RepositoriesGetRepositoryResponses = {
    /**
     * Successful Response
     */
    200: RepositoryPublic;
};

export type RepositoriesGetRepositoryResponse = RepositoriesGetRepositoryResponses[keyof RepositoriesGetRepositoryResponses];

export type RepositoriesListWorkflowFilesData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Branch
         */
        branch?: string | null;
    };
    url: '/api/v1/repositories/{repo_id}/workflow-files';
};

export type RepositoriesListWorkflowFilesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesListWorkflowFilesError = RepositoriesListWorkflowFilesErrors[keyof RepositoriesListWorkflowFilesErrors];

export type RepositoriesListWorkflowFilesResponses = {
    /**
     * Response Repositories-List Workflow Files
     * Successful Response
     */
    200: Array<WorkflowFilePublic>;
};

export type RepositoriesListWorkflowFilesResponse = RepositoriesListWorkflowFilesResponses[keyof RepositoriesListWorkflowFilesResponses];

export type RepositoriesToggleRepositoryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query: {
        /**
         * Enabled
         */
        enabled: boolean;
    };
    url: '/api/v1/repositories/{repo_id}/toggle';
};

export type RepositoriesToggleRepositoryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesToggleRepositoryError = RepositoriesToggleRepositoryErrors[keyof RepositoriesToggleRepositoryErrors];

export type RepositoriesToggleRepositoryResponses = {
    /**
     * Response Repositories-Toggle Repository
     * Successful Response
     */
    200: {
        [key: string]: string | boolean;
    };
};

export type RepositoriesToggleRepositoryResponse = RepositoriesToggleRepositoryResponses[keyof RepositoriesToggleRepositoryResponses];

export type RepositoriesToggleAutoFixData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query: {
        /**
         * Enabled
         */
        enabled: boolean;
    };
    url: '/api/v1/repositories/{repo_id}/auto-fix';
};

export type RepositoriesToggleAutoFixErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesToggleAutoFixError = RepositoriesToggleAutoFixErrors[keyof RepositoriesToggleAutoFixErrors];

export type RepositoriesToggleAutoFixResponses = {
    /**
     * Response Repositories-Toggle Auto Fix
     * Successful Response
     */
    200: {
        [key: string]: string | boolean;
    };
};

export type RepositoriesToggleAutoFixResponse = RepositoriesToggleAutoFixResponses[keyof RepositoriesToggleAutoFixResponses];

export type RepositoriesListRepositoryBranchesData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/branches';
};

export type RepositoriesListRepositoryBranchesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesListRepositoryBranchesError = RepositoriesListRepositoryBranchesErrors[keyof RepositoriesListRepositoryBranchesErrors];

export type RepositoriesListRepositoryBranchesResponses = {
    /**
     * Response Repositories-List Repository Branches
     * Successful Response
     */
    200: Array<string>;
};

export type RepositoriesListRepositoryBranchesResponse = RepositoriesListRepositoryBranchesResponses[keyof RepositoriesListRepositoryBranchesResponses];

export type RepositoriesIntegrateActionData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/repositories/{repo_id}/integrate-action';
};

export type RepositoriesIntegrateActionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RepositoriesIntegrateActionError = RepositoriesIntegrateActionErrors[keyof RepositoriesIntegrateActionErrors];

export type RepositoriesIntegrateActionResponses = {
    /**
     * Response Repositories-Integrate Action
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type RepositoriesIntegrateActionResponse = RepositoriesIntegrateActionResponses[keyof RepositoriesIntegrateActionResponses];

export type EventsGetSseSignalsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events/signals';
};

export type EventsGetSseSignalsResponses = {
    /**
     * Response Events-Get Sse Signals
     * Successful Response
     */
    200: Array<SseSignal>;
};

export type EventsGetSseSignalsResponse = EventsGetSseSignalsResponses[keyof EventsGetSseSignalsResponses];

export type EventsCreateSseTicketData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/events/ticket';
};

export type EventsCreateSseTicketResponses = {
    /**
     * Response Events-Create Sse Ticket
     * Successful Response
     */
    200: {
        [key: string]: string | number;
    };
};

export type EventsCreateSseTicketResponse = EventsCreateSseTicketResponses[keyof EventsCreateSseTicketResponses];

export type EventsStreamEventsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Ticket
         */
        ticket?: string | null;
    };
    url: '/api/v1/events/stream';
};

export type EventsStreamEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EventsStreamEventsError = EventsStreamEventsErrors[keyof EventsStreamEventsErrors];

export type EventsStreamEventsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AnalysesListAnalysesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Repo Id
         */
        repo_id?: string | null;
        /**
         * Branch
         */
        branch?: string | null;
        /**
         * Grade
         */
        grade?: string | null;
        /**
         * Status
         */
        status?: AnalysisStatus | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/analyses/';
};

export type AnalysesListAnalysesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysesListAnalysesError = AnalysesListAnalysesErrors[keyof AnalysesListAnalysesErrors];

export type AnalysesListAnalysesResponses = {
    /**
     * Response Analyses-List Analyses
     * Successful Response
     */
    200: Array<AnalysisPublic>;
};

export type AnalysesListAnalysesResponse = AnalysesListAnalysesResponses[keyof AnalysesListAnalysesResponses];

export type AnalysesGetAnalysisData = {
    body?: never;
    path: {
        /**
         * Analysis Id
         */
        analysis_id: string;
    };
    query?: never;
    url: '/api/v1/analyses/{analysis_id}';
};

export type AnalysesGetAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysesGetAnalysisError = AnalysesGetAnalysisErrors[keyof AnalysesGetAnalysisErrors];

export type AnalysesGetAnalysisResponses = {
    /**
     * Successful Response
     */
    200: AnalysisPublic;
};

export type AnalysesGetAnalysisResponse = AnalysesGetAnalysisResponses[keyof AnalysesGetAnalysisResponses];

export type AnalysesTriggerAnalysisData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Branch
         */
        branch?: string | null;
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/v1/analyses/trigger/{repo_id}';
};

export type AnalysesTriggerAnalysisErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysesTriggerAnalysisError = AnalysesTriggerAnalysisErrors[keyof AnalysesTriggerAnalysisErrors];

export type AnalysesTriggerAnalysisResponses = {
    /**
     * Response Analyses-Trigger Analysis
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type AnalysesTriggerAnalysisResponse = AnalysesTriggerAnalysisResponses[keyof AnalysesTriggerAnalysisResponses];

export type AnalysesReanalyzeForWorkflowData = {
    body?: never;
    path: {
        /**
         * Workflow File Id
         */
        workflow_file_id: string;
    };
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/v1/analyses/reanalyze-for-workflow/{workflow_file_id}';
};

export type AnalysesReanalyzeForWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnalysesReanalyzeForWorkflowError = AnalysesReanalyzeForWorkflowErrors[keyof AnalysesReanalyzeForWorkflowErrors];

export type AnalysesReanalyzeForWorkflowResponses = {
    /**
     * Response Analyses-Reanalyze For Workflow
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type AnalysesReanalyzeForWorkflowResponse = AnalysesReanalyzeForWorkflowResponses[keyof AnalysesReanalyzeForWorkflowResponses];

export type AnalysesReanalyzeAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/analyses/reanalyze-all';
};

export type AnalysesReanalyzeAllResponses = {
    /**
     * Response Analyses-Reanalyze All
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type AnalysesReanalyzeAllResponse = AnalysesReanalyzeAllResponses[keyof AnalysesReanalyzeAllResponses];

export type IssuesListIssuesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Analysis Id
         */
        analysis_id?: string | null;
        /**
         * Repo Id
         */
        repo_id?: string | null;
        /**
         * Branch
         */
        branch?: string | null;
        /**
         * Category
         */
        category?: IssueCategory | null;
        /**
         * Severity
         */
        severity?: IssueSeverity | null;
        /**
         * Unfixed
         */
        unfixed?: boolean;
        /**
         * Latest Only
         */
        latest_only?: boolean;
        /**
         * Include Resolved
         */
        include_resolved?: boolean;
        /**
         * Include Ignored
         */
        include_ignored?: boolean;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/issues/';
};

export type IssuesListIssuesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssuesListIssuesError = IssuesListIssuesErrors[keyof IssuesListIssuesErrors];

export type IssuesListIssuesResponses = {
    /**
     * Response Issues-List Issues
     * Successful Response
     */
    200: Array<IssuePublic>;
};

export type IssuesListIssuesResponse = IssuesListIssuesResponses[keyof IssuesListIssuesResponses];

export type IssuesGetIssueStatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Repo Id
         */
        repo_id?: string | null;
        /**
         * Branch
         */
        branch?: string | null;
        /**
         * Latest Only
         */
        latest_only?: boolean;
    };
    url: '/api/v1/issues/stats';
};

export type IssuesGetIssueStatsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssuesGetIssueStatsError = IssuesGetIssueStatsErrors[keyof IssuesGetIssueStatsErrors];

export type IssuesGetIssueStatsResponses = {
    /**
     * Successful Response
     */
    200: IssueStatsPublic;
};

export type IssuesGetIssueStatsResponse = IssuesGetIssueStatsResponses[keyof IssuesGetIssueStatsResponses];

export type IssuesGetIssueData = {
    body?: never;
    path: {
        /**
         * Issue Id
         */
        issue_id: string;
    };
    query?: never;
    url: '/api/v1/issues/{issue_id}';
};

export type IssuesGetIssueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssuesGetIssueError = IssuesGetIssueErrors[keyof IssuesGetIssueErrors];

export type IssuesGetIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type IssuesGetIssueResponse = IssuesGetIssueResponses[keyof IssuesGetIssueResponses];

export type IssuesIgnoreIssueData = {
    body?: never;
    path: {
        /**
         * Issue Id
         */
        issue_id: string;
    };
    query?: never;
    url: '/api/v1/issues/{issue_id}/ignore';
};

export type IssuesIgnoreIssueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssuesIgnoreIssueError = IssuesIgnoreIssueErrors[keyof IssuesIgnoreIssueErrors];

export type IssuesIgnoreIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type IssuesIgnoreIssueResponse = IssuesIgnoreIssueResponses[keyof IssuesIgnoreIssueResponses];

export type IssuesUnignoreIssueData = {
    body?: never;
    path: {
        /**
         * Issue Id
         */
        issue_id: string;
    };
    query?: never;
    url: '/api/v1/issues/{issue_id}/unignore';
};

export type IssuesUnignoreIssueErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type IssuesUnignoreIssueError = IssuesUnignoreIssueErrors[keyof IssuesUnignoreIssueErrors];

export type IssuesUnignoreIssueResponses = {
    /**
     * Successful Response
     */
    200: IssuePublic;
};

export type IssuesUnignoreIssueResponse = IssuesUnignoreIssueResponses[keyof IssuesUnignoreIssueResponses];

export type FixesListFixesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Repo Id
         */
        repo_id?: string | null;
        /**
         * Status
         */
        status?: FixStatus | null;
        /**
         * Branch
         */
        branch?: string | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/fixes/';
};

export type FixesListFixesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesListFixesError = FixesListFixesErrors[keyof FixesListFixesErrors];

export type FixesListFixesResponses = {
    /**
     * Response Fixes-List Fixes
     * Successful Response
     */
    200: Array<FixPublic>;
};

export type FixesListFixesResponse = FixesListFixesResponses[keyof FixesListFixesResponses];

export type FixesListPullRequestsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/pull-requests/{repo_id}';
};

export type FixesListPullRequestsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesListPullRequestsError = FixesListPullRequestsErrors[keyof FixesListPullRequestsErrors];

export type FixesListPullRequestsResponses = {
    /**
     * Response Fixes-List Pull Requests
     * Successful Response
     */
    200: Array<PullRequestPublic>;
};

export type FixesListPullRequestsResponse = FixesListPullRequestsResponses[keyof FixesListPullRequestsResponses];

export type FixesRejectFixData = {
    body?: never;
    path: {
        /**
         * Fix Id
         */
        fix_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/{fix_id}';
};

export type FixesRejectFixErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesRejectFixError = FixesRejectFixErrors[keyof FixesRejectFixErrors];

export type FixesRejectFixResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type FixesRejectFixResponse = FixesRejectFixResponses[keyof FixesRejectFixResponses];

export type FixesGetFixData = {
    body?: never;
    path: {
        /**
         * Fix Id
         */
        fix_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/{fix_id}';
};

export type FixesGetFixErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesGetFixError = FixesGetFixErrors[keyof FixesGetFixErrors];

export type FixesGetFixResponses = {
    /**
     * Successful Response
     */
    200: FixPublic;
};

export type FixesGetFixResponse = FixesGetFixResponses[keyof FixesGetFixResponses];

export type FixesTriggerFixGenerationForRepoData = {
    body?: BatchFixRequest;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/v1/fixes/generate-for-repo/{repo_id}';
};

export type FixesTriggerFixGenerationForRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesTriggerFixGenerationForRepoError = FixesTriggerFixGenerationForRepoErrors[keyof FixesTriggerFixGenerationForRepoErrors];

export type FixesTriggerFixGenerationForRepoResponses = {
    /**
     * Response Fixes-Trigger Fix Generation For Repo
     * Successful Response
     */
    202: {
        [key: string]: number;
    };
};

export type FixesTriggerFixGenerationForRepoResponse = FixesTriggerFixGenerationForRepoResponses[keyof FixesTriggerFixGenerationForRepoResponses];

export type FixesTriggerWorkflowDeliveryData = {
    body: WorkflowDeliverRequest;
    path?: never;
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/v1/fixes/deliver-for-workflow';
};

export type FixesTriggerWorkflowDeliveryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesTriggerWorkflowDeliveryError = FixesTriggerWorkflowDeliveryErrors[keyof FixesTriggerWorkflowDeliveryErrors];

export type FixesTriggerWorkflowDeliveryResponses = {
    /**
     * Response Fixes-Trigger Workflow Delivery
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type FixesTriggerWorkflowDeliveryResponse = FixesTriggerWorkflowDeliveryResponses[keyof FixesTriggerWorkflowDeliveryResponses];

export type FixesTriggerRepoDeliveryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Force
         */
        force?: boolean;
    };
    url: '/api/v1/fixes/deliver-for-repo/{repo_id}';
};

export type FixesTriggerRepoDeliveryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesTriggerRepoDeliveryError = FixesTriggerRepoDeliveryErrors[keyof FixesTriggerRepoDeliveryErrors];

export type FixesTriggerRepoDeliveryResponses = {
    /**
     * Response Fixes-Trigger Repo Delivery
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type FixesTriggerRepoDeliveryResponse = FixesTriggerRepoDeliveryResponses[keyof FixesTriggerRepoDeliveryResponses];

export type FixesRegenerateFixesForRepoData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/regenerate-for-repo/{repo_id}';
};

export type FixesRegenerateFixesForRepoErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesRegenerateFixesForRepoError = FixesRegenerateFixesForRepoErrors[keyof FixesRegenerateFixesForRepoErrors];

export type FixesRegenerateFixesForRepoResponses = {
    /**
     * Response Fixes-Regenerate Fixes For Repo
     * Successful Response
     */
    202: {
        [key: string]: number;
    };
};

export type FixesRegenerateFixesForRepoResponse = FixesRegenerateFixesForRepoResponses[keyof FixesRegenerateFixesForRepoResponses];

export type FixesRegenerateFixesForWorkflowData = {
    body?: never;
    path: {
        /**
         * Fix Id
         */
        fix_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/regenerate-for-workflow/{fix_id}';
};

export type FixesRegenerateFixesForWorkflowErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesRegenerateFixesForWorkflowError = FixesRegenerateFixesForWorkflowErrors[keyof FixesRegenerateFixesForWorkflowErrors];

export type FixesRegenerateFixesForWorkflowResponses = {
    /**
     * Response Fixes-Regenerate Fixes For Workflow
     * Successful Response
     */
    202: {
        [key: string]: number;
    };
};

export type FixesRegenerateFixesForWorkflowResponse = FixesRegenerateFixesForWorkflowResponses[keyof FixesRegenerateFixesForWorkflowResponses];

export type FixesRegenerateFailedFixData = {
    body?: never;
    path: {
        /**
         * Fix Id
         */
        fix_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/{fix_id}/regenerate';
};

export type FixesRegenerateFailedFixErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesRegenerateFailedFixError = FixesRegenerateFailedFixErrors[keyof FixesRegenerateFailedFixErrors];

export type FixesRegenerateFailedFixResponses = {
    /**
     * Response Fixes-Regenerate Failed Fix
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type FixesRegenerateFailedFixResponse = FixesRegenerateFailedFixResponses[keyof FixesRegenerateFailedFixResponses];

export type FixesSyncPrStatusesData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/fixes/sync-pr-status/{repo_id}';
};

export type FixesSyncPrStatusesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type FixesSyncPrStatusesError = FixesSyncPrStatusesErrors[keyof FixesSyncPrStatusesErrors];

export type FixesSyncPrStatusesResponses = {
    /**
     * Response Fixes-Sync Pr Statuses
     * Successful Response
     */
    200: {
        [key: string]: number;
    };
};

export type FixesSyncPrStatusesResponse = FixesSyncPrStatusesResponses[keyof FixesSyncPrStatusesResponses];

export type RulesListRulesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Category
         */
        category?: IssueCategory | null;
        /**
         * Enabled
         */
        enabled?: boolean | null;
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/rules/';
};

export type RulesListRulesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RulesListRulesError = RulesListRulesErrors[keyof RulesListRulesErrors];

export type RulesListRulesResponses = {
    /**
     * Response Rules-List Rules
     * Successful Response
     */
    200: Array<RulePublic>;
};

export type RulesListRulesResponse = RulesListRulesResponses[keyof RulesListRulesResponses];

export type RulesGetRuleData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query?: never;
    url: '/api/v1/rules/{rule_id}';
};

export type RulesGetRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RulesGetRuleError = RulesGetRuleErrors[keyof RulesGetRuleErrors];

export type RulesGetRuleResponses = {
    /**
     * Successful Response
     */
    200: RulePublic;
};

export type RulesGetRuleResponse = RulesGetRuleResponses[keyof RulesGetRuleResponses];

export type RulesToggleRuleData = {
    body?: never;
    path: {
        /**
         * Rule Id
         */
        rule_id: string;
    };
    query: {
        /**
         * Enabled
         */
        enabled: boolean;
    };
    url: '/api/v1/rules/{rule_id}/toggle';
};

export type RulesToggleRuleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RulesToggleRuleError = RulesToggleRuleErrors[keyof RulesToggleRuleErrors];

export type RulesToggleRuleResponses = {
    /**
     * Successful Response
     */
    200: RulePublic;
};

export type RulesToggleRuleResponse = RulesToggleRuleResponses[keyof RulesToggleRuleResponses];

export type WebhooksGithubWebhookData = {
    body?: never;
    headers?: {
        /**
         * X-Hub-Signature-256
         */
        'x-hub-signature-256'?: string | null;
        /**
         * X-Github-Event
         */
        'x-github-event'?: string | null;
        /**
         * X-Github-Delivery
         */
        'x-github-delivery'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/webhooks/github';
};

export type WebhooksGithubWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksGithubWebhookError = WebhooksGithubWebhookErrors[keyof WebhooksGithubWebhookErrors];

export type WebhooksGithubWebhookResponses = {
    /**
     * Response Webhooks-Github Webhook
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type WebhooksGithubWebhookResponse = WebhooksGithubWebhookResponses[keyof WebhooksGithubWebhookResponses];

export type BadgesGetBadgeData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Branch
         */
        branch: string;
    };
    query?: {
        /**
         * Sig
         */
        sig?: string | null;
    };
    url: '/api/v1/badges/{owner}/{repo}/{branch}.svg';
};

export type BadgesGetBadgeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BadgesGetBadgeError = BadgesGetBadgeErrors[keyof BadgesGetBadgeErrors];

export type BadgesGetBadgeResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type BadgesGetBadgeJsonData = {
    body?: never;
    path: {
        /**
         * Owner
         */
        owner: string;
        /**
         * Repo
         */
        repo: string;
        /**
         * Branch
         */
        branch: string;
    };
    query?: {
        /**
         * Sig
         */
        sig?: string | null;
    };
    url: '/api/v1/badges/{owner}/{repo}/{branch}.json';
};

export type BadgesGetBadgeJsonErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BadgesGetBadgeJsonError = BadgesGetBadgeJsonErrors[keyof BadgesGetBadgeJsonErrors];

export type BadgesGetBadgeJsonResponses = {
    /**
     * Response Badges-Get Badge Json
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BadgesGetBadgeJsonResponse = BadgesGetBadgeJsonResponses[keyof BadgesGetBadgeJsonResponses];

export type TelemetryIngestTelemetryData = {
    body: TelemetryPayload;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/telemetry/ingest';
};

export type TelemetryIngestTelemetryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryIngestTelemetryError = TelemetryIngestTelemetryErrors[keyof TelemetryIngestTelemetryErrors];

export type TelemetryIngestTelemetryResponses = {
    /**
     * Response Telemetry-Ingest Telemetry
     * Successful Response
     */
    201: {
        [key: string]: string;
    };
};

export type TelemetryIngestTelemetryResponse = TelemetryIngestTelemetryResponses[keyof TelemetryIngestTelemetryResponses];

export type TelemetryIngestSampleData = {
    body: SamplePayload;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/telemetry/sample';
};

export type TelemetryIngestSampleErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryIngestSampleError = TelemetryIngestSampleErrors[keyof TelemetryIngestSampleErrors];

export type TelemetryIngestSampleResponses = {
    /**
     * Response Telemetry-Ingest Sample
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type TelemetryIngestSampleResponse = TelemetryIngestSampleResponses[keyof TelemetryIngestSampleResponses];

export type TelemetryGetTelemetrySummaryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Skip
         */
        skip?: number;
    };
    url: '/api/v1/telemetry/summary/{repo_id}';
};

export type TelemetryGetTelemetrySummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryGetTelemetrySummaryError = TelemetryGetTelemetrySummaryErrors[keyof TelemetryGetTelemetrySummaryErrors];

export type TelemetryGetTelemetrySummaryResponses = {
    /**
     * Successful Response
     */
    200: TelemetrySummaryPublic;
};

export type TelemetryGetTelemetrySummaryResponse = TelemetryGetTelemetrySummaryResponses[keyof TelemetryGetTelemetrySummaryResponses];

export type TelemetryGetTelemetryFindingsData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/telemetry/findings/{repo_id}';
};

export type TelemetryGetTelemetryFindingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryGetTelemetryFindingsError = TelemetryGetTelemetryFindingsErrors[keyof TelemetryGetTelemetryFindingsErrors];

export type TelemetryGetTelemetryFindingsResponses = {
    /**
     * Response Telemetry-Get Telemetry Findings
     * Successful Response
     */
    200: Array<DynamicEnrichmentPublic>;
};

export type TelemetryGetTelemetryFindingsResponse = TelemetryGetTelemetryFindingsResponses[keyof TelemetryGetTelemetryFindingsResponses];

export type TelemetryAnalyzeTelemetryData = {
    body?: never;
    path: {
        /**
         * Repo Id
         */
        repo_id: string;
    };
    query?: never;
    url: '/api/v1/telemetry/analyze/{repo_id}';
};

export type TelemetryAnalyzeTelemetryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TelemetryAnalyzeTelemetryError = TelemetryAnalyzeTelemetryErrors[keyof TelemetryAnalyzeTelemetryErrors];

export type TelemetryAnalyzeTelemetryResponses = {
    /**
     * Response Telemetry-Analyze Telemetry
     * Successful Response
     */
    202: {
        [key: string]: string | number;
    };
};

export type TelemetryAnalyzeTelemetryResponse = TelemetryAnalyzeTelemetryResponses[keyof TelemetryAnalyzeTelemetryResponses];

export type BillingGetSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/billing/subscription';
};

export type BillingGetSubscriptionResponses = {
    /**
     * Successful Response
     */
    200: BillingSubscriptionPublic;
};

export type BillingGetSubscriptionResponse = BillingGetSubscriptionResponses[keyof BillingGetSubscriptionResponses];

export type BillingGetTierLimitsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/billing/limits';
};

export type BillingGetTierLimitsResponses = {
    /**
     * Response Billing-Get Tier Limits
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BillingGetTierLimitsResponse = BillingGetTierLimitsResponses[keyof BillingGetTierLimitsResponses];

export type BillingStripeWebhookData = {
    body?: never;
    headers?: {
        /**
         * Stripe-Signature
         */
        'stripe-signature'?: string | null;
    };
    path?: never;
    query?: never;
    url: '/api/v1/billing/webhook/stripe';
};

export type BillingStripeWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BillingStripeWebhookError = BillingStripeWebhookErrors[keyof BillingStripeWebhookErrors];

export type BillingStripeWebhookResponses = {
    /**
     * Response Billing-Stripe Webhook
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type BillingStripeWebhookResponse = BillingStripeWebhookResponses[keyof BillingStripeWebhookResponses];

export type TerraformListTerraformRootsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Repo Id
         */
        repo_id?: string | null;
    };
    url: '/api/v1/terraform-roots/';
};

export type TerraformListTerraformRootsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformListTerraformRootsError = TerraformListTerraformRootsErrors[keyof TerraformListTerraformRootsErrors];

export type TerraformListTerraformRootsResponses = {
    /**
     * Response Terraform-List Terraform Roots
     * Successful Response
     */
    200: Array<TerraformRootPublic>;
};

export type TerraformListTerraformRootsResponse = TerraformListTerraformRootsResponses[keyof TerraformListTerraformRootsResponses];

export type TerraformCreateTerraformRootData = {
    body: TerraformRootCreate;
    path?: never;
    query?: never;
    url: '/api/v1/terraform-roots/';
};

export type TerraformCreateTerraformRootErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformCreateTerraformRootError = TerraformCreateTerraformRootErrors[keyof TerraformCreateTerraformRootErrors];

export type TerraformCreateTerraformRootResponses = {
    /**
     * Successful Response
     */
    201: TerraformRootPublic;
};

export type TerraformCreateTerraformRootResponse = TerraformCreateTerraformRootResponses[keyof TerraformCreateTerraformRootResponses];

export type TerraformToggleTerraformRootData = {
    body?: never;
    path: {
        /**
         * Root Id
         */
        root_id: string;
    };
    query: {
        /**
         * Enabled
         */
        enabled: boolean;
    };
    url: '/api/v1/terraform-roots/{root_id}/toggle';
};

export type TerraformToggleTerraformRootErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformToggleTerraformRootError = TerraformToggleTerraformRootErrors[keyof TerraformToggleTerraformRootErrors];

export type TerraformToggleTerraformRootResponses = {
    /**
     * Response Terraform-Toggle Terraform Root
     * Successful Response
     */
    200: {
        [key: string]: string | boolean;
    };
};

export type TerraformToggleTerraformRootResponse = TerraformToggleTerraformRootResponses[keyof TerraformToggleTerraformRootResponses];

export type TerraformDeleteTerraformRootData = {
    body?: never;
    path: {
        /**
         * Root Id
         */
        root_id: string;
    };
    query?: never;
    url: '/api/v1/terraform-roots/{root_id}';
};

export type TerraformDeleteTerraformRootErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformDeleteTerraformRootError = TerraformDeleteTerraformRootErrors[keyof TerraformDeleteTerraformRootErrors];

export type TerraformDeleteTerraformRootResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TerraformDeleteTerraformRootResponse = TerraformDeleteTerraformRootResponses[keyof TerraformDeleteTerraformRootResponses];

export type TerraformTriggerTerraformScanData = {
    body?: never;
    path: {
        /**
         * Root Id
         */
        root_id: string;
    };
    query?: {
        /**
         * Branch
         */
        branch?: string | null;
    };
    url: '/api/v1/terraform-roots/{root_id}/scan';
};

export type TerraformTriggerTerraformScanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformTriggerTerraformScanError = TerraformTriggerTerraformScanErrors[keyof TerraformTriggerTerraformScanErrors];

export type TerraformTriggerTerraformScanResponses = {
    /**
     * Response Terraform-Trigger Terraform Scan
     * Successful Response
     */
    202: {
        [key: string]: string;
    };
};

export type TerraformTriggerTerraformScanResponse = TerraformTriggerTerraformScanResponses[keyof TerraformTriggerTerraformScanResponses];

export type TerraformListTerraformScansData = {
    body?: never;
    path: {
        /**
         * Root Id
         */
        root_id: string;
    };
    query?: never;
    url: '/api/v1/terraform-roots/{root_id}/scans';
};

export type TerraformListTerraformScansErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformListTerraformScansError = TerraformListTerraformScansErrors[keyof TerraformListTerraformScansErrors];

export type TerraformListTerraformScansResponses = {
    /**
     * Response Terraform-List Terraform Scans
     * Successful Response
     */
    200: Array<TerraformScanPublic>;
};

export type TerraformListTerraformScansResponse = TerraformListTerraformScansResponses[keyof TerraformListTerraformScansResponses];

export type TerraformListTerraformFindingsData = {
    body?: never;
    path: {
        /**
         * Root Id
         */
        root_id: string;
    };
    query?: {
        /**
         * Include Resolved
         */
        include_resolved?: boolean;
    };
    url: '/api/v1/terraform-roots/{root_id}/findings';
};

export type TerraformListTerraformFindingsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TerraformListTerraformFindingsError = TerraformListTerraformFindingsErrors[keyof TerraformListTerraformFindingsErrors];

export type TerraformListTerraformFindingsResponses = {
    /**
     * Response Terraform-List Terraform Findings
     * Successful Response
     */
    200: Array<TerraformFindingPublic>;
};

export type TerraformListTerraformFindingsResponse = TerraformListTerraformFindingsResponses[keyof TerraformListTerraformFindingsResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
